alias gb='git branch'
alias gcb='git checkout -b'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gfa='git fetch --all --prune --jobs=10'
alias gl='git pull'
alias gp='git push'
alias gst='git status'
